git:
  depth: 10

notifications:
  email: false

language: node_js

node_js:
  - "5.1.1"

os:
  - linux

env:
  - TARGET_ARCH=x64

osx_image: xcode7

branches:
  only:
    - master

before_install:
  - npm install -g bower gulp node-gyp

install:
  - npm install

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
