git:
  depth: 10

notifications:
  email: false

language: node_js

node_js:
  - "5.4.1"

os:
  - linux
  - osx

env:
  - TARGET_ARCH=x64

osx_image: xcode7

branches:
  only:
    - master

before_script:
  - npm install -g bower gulp node-gyp
