git:
  depth: 10

notifications:
  email: false

language: node_js

node_js:
  - "5.1.1"

os:
  - linux
  - osx

env:
  - TARGET_ARCH=x64

osx_image: xcode7

branches:
  only:
    - master

before_install:
  - npm install -g bower gulp node-gyp

install:
  - npm install npmconf@2.1.2 && node ./utils/pre-install-npm.js
  - npm install --ignore-scripts
  - git clone https://github.com/fireball-packages/package-examples ./package-examples
  - gulp update-electron
  - bower install
  - gulp npm-rebuild
  - gulp post-install-npm
  - ls
