# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    # node.js
    - nodejs_version: "5"

platform:
  - x86
  - x64

install:
  - Install-Product node "5.1.1"
  - node --version
  - npm --version
  - npm install -g bower gulp node-gyp
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

branches:
  only:
    - master
